"use client";

import { useEffect, useState } from "react";

const typeColor: Record<string, string> = {
    "pre_round": "var(--accent-purple)",
    "loss_analysis": "var(--accent-red)",
    "defense": "var(--accent-cyan)",
    "Attack": "var(--accent-red)",
    "Defense": "var(--accent-cyan)",
    "Hardpoint": "var(--accent-amber)",
};

interface DBStrategy {
    id: number;
    match_id: number;
    suggestion_type: string;
    content: string;
    confidence: number;
    created_at: string;
}

export default function PlaybookPage() {
    const [strategies, setStrategies] = useState<DBStrategy[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/api/strategies`)
            .then(res => res.json())
            .then(data => setStrategies(data))
            .finally(() => setLoading(false));
    }, []);

    // Helper to parse content if it follows our template: "Name: Description. Steps: 1. x 2. y"
    const parseContent = (content: string) => {
        const parts = content.split("Steps:");
        const main = parts[0];
        const stepsText = parts[1] || "";

        const nameDesc = main.split(":");
        const name = nameDesc[0]?.trim() || "Strategy";
        const desc = nameDesc[1]?.trim() || main;

        const steps = stepsText ? stepsText.split(/\d+\./).map(s => s.trim()).filter(Boolean) : [];

        return { name, desc, steps };
    };

    return (
        <div>
            <div className="animate-fade-in" style={{ marginBottom: "2rem" }}>
                <h1 style={{ fontSize: "1.75rem", fontWeight: 700, marginBottom: "0.25rem" }}>
                    Team <span className="gradient-text">Playbook</span>
                </h1>
                <p style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>
                    Saved strategies and setups generated by Sightline AI
                </p>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                {loading ? (
                    <div style={{ padding: "2rem", textAlign: "center", color: "var(--text-muted)" }}>Loading strategies...</div>
                ) : strategies.length === 0 ? (
                    <div style={{ padding: "2rem", textAlign: "center", color: "var(--text-muted)", background: "var(--bg-secondary)", borderRadius: "8px" }}>No strategies generated yet.</div>
                ) : strategies.map((play, i) => {
                    const parsed = parseContent(play.content);
                    return (
                        <div
                            key={play.id}
                            className={`glass-card animate-fade-in-delay-${Math.min(i, 3)}`}
                            style={{ padding: "1.5rem" }}
                        >
                            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "1rem" }}>
                                <div>
                                    <h3 style={{ fontSize: "1.0625rem", fontWeight: 600, marginBottom: "0.25rem" }}>{parsed.name}</h3>
                                    <p style={{ fontSize: "0.8125rem", color: "var(--text-secondary)", margin: 0 }}>{parsed.desc}</p>
                                </div>
                                <div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
                                    <span
                                        style={{
                                            fontSize: "0.6875rem",
                                            fontWeight: 600,
                                            padding: "0.125rem 0.5rem",
                                            borderRadius: "4px",
                                            background: `${typeColor[play.suggestion_type] || "var(--accent-purple)"}15`,
                                            color: typeColor[play.suggestion_type] || "var(--accent-purple)",
                                            textTransform: "capitalize",
                                        }}
                                    >
                                        {play.suggestion_type.replace('_', ' ')}
                                    </span>
                                </div>
                            </div>

                            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                                <div>
                                    <div style={{ fontSize: "0.75rem", color: "var(--text-muted)", marginBottom: "0.25rem" }}>Execution Steps</div>
                                    {parsed.steps.length > 0 ? (
                                        <ol style={{ margin: 0, paddingLeft: "1.25rem", display: "flex", flexDirection: "column", gap: "0.25rem" }}>
                                            {parsed.steps.map((step: string, j: number) => (
                                                <li key={j} style={{ fontSize: "0.8125rem", color: "var(--text-secondary)" }}>{step}</li>
                                            ))}
                                        </ol>
                                    ) : (
                                        <p style={{ fontSize: "0.8125rem", color: "var(--text-secondary)" }}>Execute dynamically based on call.</p>
                                    )}
                                </div>
                                <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                                    <div>
                                        <div style={{ fontSize: "0.75rem", color: "var(--text-muted)", marginBottom: "0.25rem" }}>AI Confidence Score</div>
                                        <div style={{ display: "flex", gap: "1.5rem" }}>
                                            <div>
                                                <div style={{ fontSize: "1.25rem", fontWeight: 700, color: "var(--accent-green)", fontFamily: "var(--font-mono)" }}>{(play.confidence * 100).toFixed(0)}%</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )
                })}
            </div>
        </div>
    );
}
